### ISSUE TITLE
Handle Error for Pub/Sub

### ISSUE THREAD

**Issue by mnbao1975** [nats-io/node-nats#130]
Hello,

I have Authorization for client connections for the NATS server and it works well. But, what I would like to do is how do I catch the error when the publish() is failed because of permission.

Many thanks,
Bao

**Comment by aricart** [comment]
That works out of the box. In my server I only have permissions to publish 'foo':
```
authorization {
	ADMIN = {
		publish = ">"
		subscribe = ">"
	}
	PUB = {
		publish = "foo"
	}
	SUB = {
		subscribe= "foo"
	}
	users = [
		
		{user: "admin", password: "test", permissions: $ADMIN},
		{user: "pub", password: "test", permissions: $PUB},
		{user: "sub", password: "test", permissions: $SUB},
	]
	# default of 5 seconds for an authorization timeout.
	timeout: 5.0
}
```

Now on the client side:

```
'use strict';

var nats = require('nats').connect("nats://pub:test@localhost:4222");

nats.on('error', function(e) {
  console.log("Error [" + e + "]");
  console.log(e.stack);
  process.exit();
});

function print(m) {
  console.log("message: " + m)
}

// subsription should fail
var ssid = nats.publish("bar", print)
```

When the code runs, the error handler gets invoked:
```
[xxx@barsoom:/private/tmp/permtest]$ node testpub.js
Error [NatsError: 'Permissions Violation for Publish to "bar"']
NatsError: 'Permissions Violation for Publish to "bar"'
    at Client.processInbound (/private/tmp/permtest/node_modules/nats/lib/nats.js:788:30)
    at Socket.<anonymous> (/private/tmp/permtest/node_modules/nats/lib/nats.js:468:12)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:172:18)
    at Socket.Readable.push (_stream_readable.js:130:10)
    at TCP.onread (net.js:535:20)
```

If this doesn't work for you please feel free to open a new issue. Thanks.

**Comment by mnbao1975** [comment]
Many thanks aricart. The doc should be updated.

Bao
