### ISSUE TITLE
If nats.connect(url), then connection.reconnect cannot work

### ISSUE THREAD

**Issue by zhaoyao91** [nats-io/node-nats#160]
If I get connection from nats.connect(url) instead of nats.connect(options), then connection.reconnect() cannot work.

```
> nc.reconnect()
TypeError: Cannot read property 'url' of undefined
    at Client.selectServer (C:\Users\zhaoyao\Desktop\test-nats\node_modules\nats\lib\nats.js:332:22)
    at Client.createConnection (C:\Users\zhaoyao\Desktop\test-nats\node_modules\nats\lib\nats.js:556:8)
    at Client.reconnect (C:\Users\zhaoyao\Desktop\test-nats\node_modules\nats\lib\nats.js:1328:8)
    at repl:1:4
    at ContextifyScript.Script.runInThisContext (vm.js:44:33)
    at REPLServer.defaultEval (repl.js:239:29)
    at bound (domain.js:301:14)
    at REPLServer.runBound [as eval] (domain.js:314:12)
    at REPLServer.onLine (repl.js:440:10)
    at emitOne (events.js:120:20)
```

**Comment by zhaoyao91** [comment]
sorry, it's because it failed the first  time to connect to nats.
