### ISSUE TITLE
Authorization violation error and maxReconnectAttempts issue

### ISSUE THREAD

**Issue by valichek** [nats-io/node-nats#175]
Authorization violation error is emitted every second time when reconnecting. If I set `maxReconnectAttempts` to `0`. No error event received then.

**Comment by aricart** [comment]
@valichek likely then you have an authorization validation. What does your server configuration and client configuration look like? Setting `maxReconnectAttemts` to 0, effectively prevents the client from reconnecting if it fails to connect the first time.

**Comment by valichek** [comment]
@aricart
these are the only parameters for client I have:
```
{
  token: "",
  maxReconnectAttempts: 0,
  preserveBuffers: true
}
```
Server closes connection right after sending `Authorization violation` error to the client. So if no reconnect - no error emitted from client.

**Comment by valichek** [comment]
The problem is that client doesn't emit `Authorization violation` if `maxReconnectAttemts = 0`. I can get it only when `maxReconnectAttemts > 0` But again it is emitted not every time when received from server.

**Comment by aricart** [comment]
I am not able to reproduce your issue. Do you have a cluster? I get one notification

```
'use strict';

var NATS = require('../');

var nc = NATS.connect({maxReconnectAttempts: 0, token: 'b', preserveBuffers: true});

nc.on('error', function(e) {
    console.error('error', e);
});

nc.on('created', (id) => console.log('created connection', id));
nc.on('disconnect', () => console.log('disconnected'));
nc.on('reconnecting', () => console.log('reconnecting'));
nc.on('close', () => console.log('close'));
nc.on('connect', () => console.log('initial connect'));
```

If I run this:
```
[albertoricart@barsoom:~]$ gnatsd -auth 'foo'
[6073] 2017/11/09 09:47:22.479713 [INF] Starting nats-server version 1.0.4
[6073] 2017/11/09 09:47:22.479859 [INF] Listening for client connections on 0.0.0.0:4222
[6073] 2017/11/09 09:47:22.479866 [INF] Server is ready
[6073] 2017/11/09 09:47:37.308459 [ERR] 127.0.0.1:61200 - cid:1 - Authorization Error
```
I get, one error every time.

```
[albertoricart@barsoom:~/go/src/git...e-nats/examples]$ node connecthandlers.js 
error { NatsError: 'Authorization Violation'
    at Client.processErr (/Users/albertoricart/go/src/github.com/nats-io/node-nats/lib/nats.js:1054:28)
    at Client.processInbound (/Users/albertoricart/go/src/github.com/nats-io/node-nats/lib/nats.js:827:28)
    at Socket.<anonymous> (/Users/albertoricart/go/src/github.com/nats-io/node-nats/lib/nats.js:501:16)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:172:18)
    at Socket.Readable.push (_stream_readable.js:130:10)
    at TCP.onread (net.js:535:20)
  name: 'NatsError',
  message: '\'Authorization Violation\'',
  code: 'NATS_PROTOCOL_ERR',
  chainedError: undefined }
disconnected
close
```
