### ISSUE TITLE
After upgrade I get 'Authorization Violation' errors

### ISSUE THREAD

**Issue by StarpTech** [nats-io/node-nats#181]
Hi, after upgrading NATS I get issues about 'Authorization Violation' errors. I can't reproduce it on locally on Windows but on Appveyor or Travis https://travis-ci.org/hemerajs/hemera/jobs/318878569 Do you know what could get wrong? 
```
1) Timeouts

       Should be able listen on client timeout events in onClientPostRequest:

     Uncaught NatsError: 'Authorization Violation'

      at Client.processErr (node_modules/nats/lib/nats.js:1006:28)

      at Client.processInbound (node_modules/nats/lib/nats.js:780:28)

      at Socket.<anonymous> (node_modules/nats/lib/nats.js:457:16)

      at addChunk (_stream_readable.js:263:12)

      at readableAddChunk (_stream_readable.js:250:11)

      at Socket.Readable.push (_stream_readable.js:208:10)

      at TCP.onread (net.js:594:20)


  2) Timeouts

       "after all" hook:

     Uncaught TypeError: Cannot read property 'isPending' of undefined
```

**Comment by StarpTech** [comment]
Can be closed. It was a wrong nats connection string in my tests. But very interesting that `authorization` issues weren't thrown before :/

**Comment by aricart** [comment]
What version did you upgrade to? Current on npm?

**Comment by StarpTech** [comment]
Yes, I upgraded to 0.7.2 to 0.7.24
