### ISSUE TITLE
Error on client.connect(url)

### ISSUE THREAD

**Issue by RomaOrlov** [nats-io/node-nats#240]
```
var u = new URL(url);
            ^
ReferenceError: URL is not defined
    at sanitizeUrl (/home/roma/node/message-broker/node_modules/nats/lib/nats.js:377:13)
    at Client.parseOptions (/home/roma/node/message-broker/node_modules/nats/lib/nats.js:270:23)
    at new Client (/home/roma/node/message-broker/node_modules/nats/lib/nats.js:181:10)
    at new exports.connect (/home/roma/node/message-broker/node_modules/nats/lib/nats.js:209:12)
    at NatsEventBus.getClient (/home/roma/node/message-broker/event-bus/nats-event-bus.js:49:12)
    at new NatsEventBus (/home/roma/node/message-broker/event-bus/nats-event-bus.js:18:24)
    at NatsEventBusFactory.create (/home/roma/node/message-broker/event-bus/nats-event-bus-factory.js:9:12)
    at new MessageBroker (/home/roma/node/message-broker/libs/message-broker.js:6:38)
    at Object.<anonymous> (/home/roma/node/message-broker/test.js:34:12)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
```

**Comment by StarpTech** [comment]
@RomaOrlov which node version are you using? `URL` was added in v7.0.0, v6.13.0, v10.0.0

**Comment by RomaOrlov** [comment]
8 and 9. Thank you!
