### ISSUE TITLE
Release 1.2.0 contains backward incompatible changes

### ISSUE THREAD

**Issue by eonicle** [nats-io/node-nats#241]
Release 1.2.0 introduces use of [URL class](https://nodejs.org/api/url.html#url_url) (probably added [here](https://github.com/nats-io/node-nats/pull/239)), which leads projects using NodeJS version prior to 10 to break as described [here](https://github.com/nats-io/node-nats/issues/240). Shouldn't changes of this kind be at least implemented as major version? We have a lot of projects using this module as dependency matched for minor version, which makes it impossible to update dependencies now. Shouldn't we follow SemVer  and move those changes as major release?

**Comment by derekcollison** [comment]
Thanks for the feedback. Let me take a quick look later today and see what we can do. Don't want to be breaking folks.

**Comment by derekcollison** [comment]
Which version does it break? Node.js prior to version 8?

**Comment by eonicle** [comment]
All versions prior to 10. I have projects on 8 and 9, and did some research on 6 and 7, which should work, but they actually don't:
```
> process.versions.node
'7.10.1'
> const myURl = new URL("http://test.com");
ReferenceError: URL is not defined
    at repl:1:19
    at ContextifyScript.Script.runInThisContext (vm.js:23:33)
    at REPLServer.defaultEval (repl.js:339:29)
    at bound (domain.js:280:14)
    at REPLServer.runBound [as eval] (domain.js:293:12)
    at REPLServer.onLine (repl.js:536:10)
    at emitOne (events.js:101:20)
    at REPLServer.emit (events.js:191:7)
    at REPLServer.Interface._onLine (readline.js:241:10)
    at REPLServer.Interface._line (readline.js:590:8)
```

```
> process.versions.node
'6.14.4'
> const myURl = new URL("http://test.com");
ReferenceError: URL is not defined
    at repl:1:19
    at sigintHandlersWrap (vm.js:22:35)
    at sigintHandlersWrap (vm.js:73:12)
    at ContextifyScript.Script.runInThisContext (vm.js:21:12)
    at REPLServer.defaultEval (repl.js:340:29)
    at bound (domain.js:280:14)
    at REPLServer.runBound [as eval] (domain.js:293:12)
    at REPLServer.<anonymous> (repl.js:539:10)
    at emitOne (events.js:101:20)
    at REPLServer.emit (events.js:188:7)
```

**Comment by eonicle** [comment]
It looks like the only place URL is used is [here](https://github.com/nats-io/node-nats/blob/43e2aca423bf2900ef6eb8ec54e095b9a0336d87/lib/nats.js#L372). So maybe only this function could be rewritten to use NodeJS default url module?

```
const url = require('url');
url.parse(myurl).port;
```

**Comment by derekcollison** [comment]
Will take a look. Thanks again.

**Comment by derekcollison** [comment]
ok fixed, will get @aricart to do a release at some point today.
